services:
  redis:
    image: redis:8
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

  db:
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongodata:/data/db
    ports:
      - "${MONGO_PORT}:27017"

  api:
    build: ./backend
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - db
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DB: ${MONGO_DB}
      MONGO_PORT: ${MONGO_PORT}

volumes:
  mongodata:
